import type { Metadata } from "next";
import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";
import { BookOpenIcon, HomeIcon, Gamepad2Icon, UserIcon } from "lucide-react";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
const bebas = Bebas_Neue({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(bebas.className, "dark bg-gray-950")}>
        <div className="bg-gradient-to-t to-sky-950/50 via-transparent  from-red-950/50 flex flex-col h-screen">
          <Header />
          <div className="flex-1 flex w-full">
            <SideBar />
            <div className="flex-1">
              {children}
            </div>
            
          </div>
        </div>

        <Toaster />
      </body>
    </html>
  );
}

const SideBar = () => {
  const routes = [
    {
      name: "Home",
      icon: (props) => <HomeIcon {...props} />,
      href: "/",
    },
    {
      name: "Library",
      icon: (props) => <BookOpenIcon {...props} />,
      href: "/lobby",
    },
    {
      name: "Play",
      icon: (props) => <Gamepad2Icon {...props} />,
      href: "/play",
    },
    {
      name: "Profile",
      icon: (props) => <UserIcon {...props} />,
      href: "/profile",
    },
  ];
  return (
    <nav className="w-24 h-full bg-gray-950/40 border-r border-red-500">
      <div className="flex flex-col items-center">
        {routes.map((route) => (
          <Link className="p-8" key={route.name} href={route.href}>
            <div>
              <route.icon className="h-8 w-8" />
            </div>
          </Link>
        ))}
      </div>
    </nav>
  );
};
