import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";
import Script from "next/script";
import { SideBar } from "@/components/layout/side-bar";
import { ActivityBar } from "@/components/layout/activity-bar";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "QuizBlitz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "dark  bg-[#1d2229]")}>
        <div className="flex h-screen ">
          <SideBar />
          <div className="flex-1 flex flex-col w-full bg-[#1a1e24] ">
            {children}
          </div>
          <ActivityBar />
        </div>
        <Script src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></Script>
        <Toaster />
      </body>
    </html>
  );
}